Logistic:
  Run: True
  GridCV: False
  Penalty: 'l2' #found after running GridCV
  C: 0.001 #found after running GridCV
  Solver: 'liblinear' #found after running GridCV

RandomForest:
  Run: True
  GridCV: False
  MaxDepth: 23 #found after running GridCV

KNN:
  Run: True
  GridCV: False
  N_Neighbors: 1 #found after running GridCV